app/website/models.py
from website import db
from datetime import datetime

class BlogPosts(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    title = db.Column(db.String(200))

    text = db.Column(db.Text())

    datetime = db.Column(db.DateTime(), default=datetime.now())

app/website/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
import logging as log
import json
from pathlib import Path

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config['ROOT'] = Path(__file__).parent

    with open(str(app.config['ROOT'] / Path('config.json'))) as conf:
        config = json.load(conf)

        # The webserver secret key.
        app.config['SECRET_KEY'] = config['SECRET_KEY']

        # SQLAlchemy URI defines how to connect to Postgres.
        app.config['SQLALCHEMY_DATABASE_URI'] = config['SQLALCHEMY_DATABASE_URI']

    print(app.config['SQLALCHEMY_DATABASE_URI'])

    db.init_app(app=app)

    from website.main.routes import main
    app.register_blueprint(main)

    app.logger.info('Configured App')

    return app

app/website/main/routes.py
from flask import render_template, Blueprint, redirect, url_for, current_app, flash, current_app
from flask_login import current_user, login_required
from website.models import BlogPosts
from pathlib import Path
from datetime import datetime

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index')
def index():
    """
    Flask route that returns webpage for info on the project.

    :return: Rendered index.html webpage.
    """

    return render_template('index.html')

@main.route('/blog/<int:page>')
def blog(page=1):
    """
    Flask route that returns webpage for info on the project.

    :return: Rendered index.html webpage.
    """

    pagination = BlogPosts.query.order_by(BlogPosts.datetime.desc()).paginate(page=page)

    return render_template('blog.html', pagination=pagination)

@main.route('/documents')
def documents():
    """
    Flask route that returns webpage for info on the project.

    :return: Rendered index.html webpage.
    """

    filesFolder = current_app.config['ROOT'] / Path('static/files')

    files = []

    for path in filesFolder.iterdir():
        fileTime = datetime.fromtimestamp(path.lstat().st_mtime)
        files.append((path.name, fileTime.strftime('%Y-%m-%d %H:%M:%S')))

    return render_template('documents.html', files=files)

app/website/templates/blog.html

{% extends 'site.html' %}
{% block content %}

<section>
  <div class="jumbotron text-center mt-2" style="background-color: transparent">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h1>Blog</h1>
          <p>Want to know more about me?</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section> 
  <!-- Accordion code https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_accordion_animate -->
  <div class="container">
    <div class="page-items text-center mb-4">
      Showing Results: {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
    </div>
    {% for post in pagination %}
    <button class="accordion rounded" style="color: black;"><strong>{{ post.title }}, {{ post.datetime }}</strong></button>
    <div class="panel">
      <p>{{ post.text }}</p>
    </div>
    {% endfor %}

    <ul class="pagination justify-content-center mt-4">
      {% for page in pagination.iter_pages() %}
      <li class="page-item"><a class="page-link" href="{{ url_for('main.blog', page=page) }}">{{ page }}</a></li>
      {% endfor %}
    </ul>
  </div>
</section>

{% endblock %}

app/website/templates/documents.html

{% extends 'site.html' %}
{% block content %}

<section>
  <div class="jumbotron text-center mt-2" style="background-color: transparent">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h1>Documents</h1>
          <p>Transcripts, Resume, Papers, Etc.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container text-center justify-content-center">
    <table class="rounded mt-5" style="margin-left: auto; margin-right: auto;">
      <thead>
        <tr>
          <th>Files</th>
          <th>Date & Time</th>
        </tr>
      </thead>
      <tbody>
        {% for file in files %}
        <tr style="padding: 10px;">
          <td><a href="{{ url_for('static', filename='files/'+file[0]) }}" download>
            <button class="file rounded">{{ file[0] }} <i class="fa fa-download"></i></button></td>
          </a>
          <td>{{ file[1] }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>

{% endblock %}

app/website/templates/index.html

{% extends 'site.html' %}
{% block content %}

<section>
  <div class="jumbotron text-center mt-2" style="background-color: transparent">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h1>Hello, I'm Hank Murdock.</h1>
          <p>Computer Science Student at Michigan State University</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container text-center">
    <h1>Experience</h1>
    <div class="container mt-4 text-center">
      <a href="{{ url_for('static', filename='files/resume.pdf') }}" download><button class="btn"><i class="fa fa-download"></i> Resume Download</button></a>
    </div>
    <div class="row mt-4">
      <div class="col mt-4"> <a href="https://www.kla.com/" style="text-decoration: none">
        <div class="card" id="kla">
          <div class="card-header"><strong style="color: black">KLA Software Intern, Summer 2023</strong></div>
          <div class="card-img mt-4 mb-4"><img class="rounded-circle" src="{{ url_for('static', filename='kla.jpeg') }}" width="200" height="200" alt="KLA"/></div>
        </div>
        </a> </div>
      <div class="col mt-4"> <a href="https://msu.edu/" style="text-decoration: none">
        <div class="card" id="michigan-state">
          <div class="card-header"><strong style="color: black">Teaching Assistant, Data Structures and Algorithms</strong></div>
          <div class="card-img mt-4 mb-4"><img src="{{ url_for('static', filename='msu.png') }}" width="200" height="200" alt="Michigan State University"/></div>
        </div>
        </a> </div>
    </div>
  </div>
</section>

{% endblock %}

app/website/templates/site.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hank Murdock</title>
<!-- Bootstrap -->
<link href="{{ url_for('static', filename='bootstrap-4.4.1.css') }}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="icon" href="{{ url_for('static', filename='logo.jpeg') }}" type="image/x-icon">
<style type="text/css">
  
body {
    background-image: url();
}
</style>
<link href="{{ url_for('static', filename='extra.css') }}" rel="stylesheet" type="text/css">
</head>
<body>
<nav class="navbar navbar-expand-lg mt-2"> <a class="navbar-brand zoom mr-5" href="{{ url_for('main.index') }}"><img src="{{ url_for('static', filename='logo.jpeg') }}" class="rounded-circle" width="50" height="50" alt="HM"/></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"><i class="fa fa-navicon"></i></span> </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item zoom mr-5"><a class="nav-link" href="{{ url_for('main.blog', page=1) }}" style="color: dodgerblue">
        <h3>Blog</h3>
        </a></li>
      <li class="nav-item zoom mr-5"><a href="{{ url_for('main.documents') }}" class="nav-link" style="color: dodgerblue">
        <h3>Documents</h3>
        </a></li>
      <li class="nav-item zoom mr-5"><a href="https://www.linkedin.com/in/henry-murdock/"><img src="{{ url_for('static', filename='linkedin.png') }}" id="linkedin" class="rounded-circle" width="50" height="50" alt="LinkedIn"/></a></li>
      <li class="nav-item zoom mr-5"><a href="https://github.com/Murdock022X"><img src="{{ url_for('static', filename='github.png') }}" id="github" class="rounded-circle" width="50" height="50" alt="Github"/></a></li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

<div class="section mt-5">
  <div class="container">
    <div class="card">
      <h5 class="text-center text-muted mt-3">Get In Touch&nbsp;</h5>
      <address class="text-center">
      <h2><a href="mailto:hankmurdock@gmail.com">hankmurdock@gmail.com</a></h2>
      </address>
    </div>
  </div>
</div>
<hr>
<footer class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>Copyright © . All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>
<script src="{{ url_for('static', filename='accordion.js') }}"></script> 
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script src="{{ url_for('static', filename='jquery-3.4.1.min.js') }}"></script> 
<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script src="{{ url_for('static', filename='popper.min.js') }}"></script> 
<script src="{{ url_for('static', filename='bootstrap-4.4.1.js') }}"></script>

</body>
</html>